# working_directory = "~/Desktop/"
working_directory = "/Users/axit/Desktop/"
# working_directory = "None"

[font]
size = 19.0 

[font.normal]
family="BlexMono Nerd Font"

[window]
opacity=0.97
startup_mode = "Windowed"
decorations = "Buttonless"
dynamic_padding = true
option_as_alt = "Both"

#make this italic


[mouse]
hide_when_typing= true


[window.padding]
x = 5 
y = 6 


[colors.normal]
black = "#1d3b53"
red = "#fc514e"
green = "#a1cd5e"
yellow = "#e3d18a"
blue = "#82aaff"
magenta = "#c792ea"
cyan = "#7fdbca"
white = "#a1aab8"


[colors.primary]
background="#011627"

[colors.cursor]
text = "CellBackground"
cursor = "CellForeground"





